### PR TITLE
pat-blink: Signal urgency or importance

### PR DESCRIPTION
**Pull request by chaoflow**

### CODE REVIEW

**Comment by cornae** [comment]
Isn't this some presentational feature that one would solve with CSS?

**Comment by chaoflow** [comment]
The chosen implementation ensures that all blink elements within a page are synchronized, even if injected later.

**Comment by pysailor** [comment]
I think it is a worthy addition to Patternslib! It addresses the number one issue on this list: http://www.tamaraolsondesigns.com/five-retro-geocities-era-web-patterns-worth-resurrecting/

I would love to also see a pat-under-construction soon.

**Comment by jcbrand** [comment]
<3

**Comment by cornae** [comment]
Hehe ;)

**Comment by cornae** [comment]
Yes, I think there's plenty of reason to seriously consider this. :)

**Comment by pilz** [comment]
@cornae I would actually nearly tend to merge this now :) Any objections? After all we are neglecting the really important things way too often…
As a tradeoff, you perhaps don't need to design a documentation tile for the website though.

**Comment by cornae** [comment]
Maybe next April ;)
Op do 25 aug. 2016 om 09:13 schreef Alexander Pilz <notifications@github.com

**Comment by pilz** [comment]
Closing until next April

**Comment by cornae** [comment]
;)


Op di 30 aug. 2016 om 13:52 schreef Alexander Pilz <notifications@github.com

**Pull request closed without merging**
