### PR TITLE
New pattern: datetimepicker, Masonry enhancements

### PR DESCRIPTION
**Pull request by thet**
This targets the 2.1.x branch. A forward port to master is at: https://github.com/Patternslib/Patterns/pull/575

## pat-masonry
 - Re-Layout on ``load`` events emitted on ``img`` nodes within the masonry scope.
 - Do not depend on ``imagesloaded``.
 - Update masonry to version 4.2.0.
 - Align options with new version:
   - Add options ``is-horizontal-order``, ``is-percent-position`` and ``is-resize``.
   - Remove options ``visible-style`` and ``hidden-style``.
   - Add Aliases from v4 (no ``is-*``) to v3 names (with ``is-`` for booleans), while keeping the v3 names. The patternslib parser does boolean casting for ``is-*`` options.

## pat-datetime-picker
- Add new pattern for setting the date and time.

## pat-date-picker
- Remove the dependency on ``moment-timezone-data`` - it's not used and there is no use in a date picker anyways.

## Makefile
- with the ``clean`` target, also remove the ``stamp-bundler`` marker file.

### CODE REVIEW

**Comment by thet** [comment]
why closed?

**Comment by pilz** [comment]
oops, I didn't consciously close this… Probably I mis-picked in waffle.

**Comment by pilz** [comment]
Dammit, why can't I reopen this?

**Comment by thet** [comment]
ok :)
these changes can probably soon be merged. just have to review myself

**Comment by pilz** [comment]
Can you see what happened here? What did I do to not being able to reopen this?

**Comment by thet** [comment]
hm. did you delete the 2.1.x branch too? it's targeted to 2.1.x branch, my "reopen" button says it's gone.

**Comment by pilz** [comment]
aaaah, dammit, I that was it. I thought that was a stale branch that I don't need anymore.

**Comment by thet** [comment]
maybe i created it to have a 2.1.x release branch.
i recreate it, ok?

**Comment by pilz** [comment]
A warning would have been nice. Any suggestion how to save the day?

**Comment by pilz** [comment]
yes, please!

**Comment by thet** [comment]
done.
i promise, i'll finish this PR so that it can be merged soon!

**Comment by pilz** [comment]
Aaah, super. And I promise to keep my fingers away until after xmas…

**Comment by pilz** [comment]
Sorry ;)

**Comment by thet** [comment]
no problem :)

**Comment by thet** [comment]
Ready to review!

I'll prepare a PR for master.
The tests for date-picker don't run (they were also not included before...) but I wrote tests for the new  datetime-picker.

Despite of the initial scope of only adding a datetime picker, I extended this PR to also include updates to pat-masonry.

**Comment by pilz** [comment]
I am still recovering from a heavy flu. I have this on my list, need a bit more time.

**Comment by jensens** [comment]
LGTM, when can we expect a merge?

**Comment by pilz** [comment]
Sorry for the delay!

**Comment by jensens** [comment]
Thanks!

**Comment by jensens** [comment]
@thet oh, this is on the branch, so master would need this too?

**Comment by thet** [comment]
@jensens yes, but there are some test failures to resolve: https://github.com/Patternslib/Patterns/pull/575

master is webpack based. Plone uses currently the non-webpack 2.1.x branch.

**Pull request merged**
