### PR TITLE
DO NOT MERGE: jquery-migrate WIP

### PR DESCRIPTION
**Pull request by fulv**

### CODE REVIEW

**Comment by fulv** [comment]
For the record:  

    WARN: 'JQMIGRATE: jQuery.fn.load() is deprecated'

This is caused by the `jquery.anythingslider` plugin, which has jQuery pinned at `">=1.4.2"`, so it's probably expected to work even with old versions of jQuery.

**Comment by fulv** [comment]
The warning

    WARN: 'JQMIGRATE: $(html) HTML text after last tag is ignored'

was caused by this type of code, which was repeated in multiple places:

    var $el = $('<div class="pat-stacks"></div');

Note the missing final angle bracket.  I'm not sure if this was intentional, or simply a typo that proliferated due to copy & paste.

Ref:  https://github.com/jquery/jquery-migrate/blob/1.x-stable/warnings.md#jqmigrate-html-text-after-last-tag-is-ignored

**Comment by fulv** [comment]
Now we only have the following warnings left:

WARN: 'JQMIGRATE: jQuery.browser is deprecated'
WARN: 'JQMIGRATE: jQuery.browser is deprecated'
WARN: 'JQMIGRATE: jQuery.fn.load() is deprecated'
WARN: 'JQMIGRATE: jQuery.fn.load() is deprecated'
WARN: 'JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8'
WARN: 'JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8'
WARN: 'JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8'
WARN: 'JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8'

[The first one](https://github.com/jquery/jquery-migrate/blob/1.x-stable/warnings.md#jqmigrate-jquerybrowser-is-deprecated) is probably going to be tricky.
This can probably be remedied by judicious use of  http://api.jquery.com/jQuery.support/, or modernizr.

[`fn.load()`](https://github.com/jquery/jquery-migrate/blob/1.x-stable/warnings.md#jqmigrate-jqueryfnload-is-deprecated), as mentioned in an earlier comment, is caused by `jquery.anythingslider`, which is only used by `carousel-legacy`.  Not sure if we should drop this at some point, or build it with our own fork of anythingslider.

The [JQMIGRATE: Can't change the 'type' of an input or button in IE 6/7/8](https://github.com/jquery/jquery-migrate/blob/1.x-stable/warnings.md#jqmigrate-cant-change-the-type-of-an-input-or-button-in-ie-678) can safely be ignored, in my opinion.

Please evaluate whether to merge this now, to provide a baseline for further upgrade to jQuery 3.  Either way, I'm planning on building on top of this branch for further migration work.

**Comment by fulv** [comment]
I'll leave the tests to fail until I'm done with all the fixes, instead of adding jquery-migrate.

**Comment by pilz** [comment]
Really nice progress. 
Note that we don't really support IE6/7/8/9 and even 10 is out of scope as it is not even supported by MS anymore. I believe to remember that the jquery.browser stuff was to work around some old IE bugs. If that is correct, I would be fine by removing that compatibility code instead of doing a costly replacement of jq.browser.

**Comment by fulv** [comment]
@pilz good to know, I will keep that in mind.

**Comment by fulv** [comment]
I figured out the issue:

    WARN: 'JQMIGRATE: jQuery.fn.offset() requires an element connected to a document'

It comes from select2:  https://github.com/select2/select2/issues/5173

I have not tried different versions of select2 to see whether it goes away, because the above issue is still open, so I guess there is nothing we can do.  
From what I can see, there i no other code causing this warning other than select2.

**Comment by fulv** [comment]
And this concludes the migration.  The remaining warnings are all due to external dependencies, i.e. select2 and anythingslider:

```
WARN: 'JQMIGRATE: jQuery.fn.bind() is deprecated'                                                                                                                                    
WARN: 'JQMIGRATE: jQuery.fn.bind() is deprecated'                                                                                                                                    
WARN: 'JQMIGRATE: jQuery.fn.unbind() is deprecated'                                                                                                                                  
WARN: 'JQMIGRATE: jQuery.fn.unbind() is deprecated'                                                                                                                                  
WARN: 'JQMIGRATE: jQuery.fn.load() is deprecated'                                                                                                                                    
WARN: 'JQMIGRATE: jQuery.fn.load() is deprecated'                                                                                                                                    
WARN: 'JQMIGRATE: jQuery.fn.offset() requires an element connected to a document'                                                                                                    
WARN: 'JQMIGRATE: jQuery.fn.offset() requires an element connected to a document'                                                                                                   
``` 


I verified this by hacking select2 and anythingslider in node_modules, and by doing so I was able to get a totally clean test run.

Next steps:
- Update the dependencies which are mentioned by npm and github as outdated or containing vulnerabilities by uppinning
- Checking tests again
- Creating a test bundle and run our integration tests with the new jquery bundle 
- Do manual tests with the new bundle.

**Comment by pilz** [comment]
Excellent. Can you try to merge current master in? I think it already works with a modern select2, that might fix it. Perhaps there is also a newer version of anythingslider? 

https://github.com/patternslib/Patterns/network/dependencies shows 11 vulnerabilities, the next step should be to upgrade them to latest version and check again.

**Comment by fulv** [comment]
@pilz where do you see those 11 vulnerabilities?  When I go to https://github.com/patternslib/Patterns/network/dependencies, I can't find anything related to vulnerabilities.

**Comment by pilz** [comment]
Hi Fulvio,

I see this:



All the yellow stuff seems to have some issues. Perhaps you need to be admin to see this?

Von meinem iPad gesendet

**Comment by fulv** [comment]
I can only guess since your screenshot did not make it.  But yeah, that's
probably only visible to you.

**Comment by fulv** [comment]
The `.pat-equalizer` failures seem to be a heisenbug.  I get them sporadically on local, but usually, they disappear on the next run.

**Comment by pilz** [comment]
latest npm gives even more info on vulnrabilities and apparently proposes to auto-fix:

This was among the output of a make bundle in patterns

added 1588 packages from 1328 contributors and audited 11434 packages in 30.767s
found 375 vulnerabilities (289 low, 38 moderate, 48 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by fulv** [comment]
Unfortunately:

```
 > npm audit                                                                                                                                                                      
npm ERR! code E400                                                                                                                                                               
npm ERR! 400 Bad Request - POST https://registry.npmjs.org/-/npm/v1/security/audits 
```

And that is after removing the `AnythingSlider` dependency from package.json, which prevents `npm audit` from running at all.  There are two dependencies on AnythingSlider, one in lowercase and one in CamelCase.  In my opinion, the CamelCase one needs to be deleted.

But the bigger issue is the E400 error.  I'm almost sure (but could be wrong) that I was able to successfully run `npm audit` a few days ago, so I'm not sure what the issue is.

**Comment by fulv** [comment]
After a lot of debugging, I narrowed it down to this:  any empty string in dependencies versions causes the E400 Bad Request (https://npm.community/t/npm-audit-returns-error-code-e400-when-dependency-has-empty-string-instead-of-version-number/2044).  
So I manually pinned all the missing versions according to the output of `npm list --depth=0`.  Now I get a useful output from `npm audit` that I can work with.

**Comment by fulv** [comment]
The next step is something like:

```
67c67                                                                                                                                                                                
<     "jasmine-core": "^2.8.0",                                                                                                                                                      
---                                                                                                                                                                                  
>     "jasmine-core": "^3.2.0",                                                                                                                                                      
70c70                                                                                                                                                                                
<     "karma": "^1.7.1",                                                                                                                                                             
---                                                                                                                                                                                  
>     "karma": "^3.0.0",                                                                                                                                                             
90c90                                                                                                                                                                                
<     "webpack-karma-jasmine": "^1.0.4",                                                                                                                                             
---                                                                                                                                                                                  
>     "webpack-karma-jasmine": "^3.0.0",                                                                                                                                             
```

This would resolve the majority of the remaining vulnerabilities.  However, it causes the tests to stop working, and also some peerDependency problems:

```
npm WARN jasmine-webpack-plugin@0.1.1 requires a peer of jasmine-core@^2.3.4 but none is installed. You must install peer dependencies yourself.                                     
npm WARN webpack-jasmine-html-runner-plugin@0.8.0 requires a peer of jasmine-core@^2.5.2 but none is installed. You must install peer dependencies yourself.                         
```

jasmine-webpack-plugin, modernizr-webpack-plugin and phantom-jasmine also have vulnerabilities but have not seen new releases in a long time, so it will take a while to fix those.

The biggest problem, though, is getting tests to run with upgraded karma and jasmine stuff.

**Comment by fulv** [comment]
Current status:

```
found 30 vulnerabilities (22 low, 8 high) in 18224 scanned packages                                                                                                                  
  24 vulnerabilities require semver-major dependency updates.                                                                                                                        
  6 vulnerabilities require manual review. See the full report for details.                                                                                                          
```

**Comment by fulv** [comment]
We are down to just 4 low severity vulnerabilities 🙌 
`modernizr` already has a merged PR to fix one of those, and `modernizr-webpack-plugin` has an open PR that would update its `html-webpack-plugin` dependency, which in turn fixes the `lodash` vulnerability.  So we could get to 0 in short order.  `jasmine-webpack-plugin` has not been maintained in 3 years, and I wonder if we really need it.

Sorry it took so long!  The silver lining is that one of the main problematic dependencies (`karma-webpack`) has seen a flurry of new releases in the last few weeks, fixing a bunch of issues and vulnerabilities, so we get those for free.

Tests are a bit brittle, with a few heisenbugs. There is a bunch of test cleanup I want to do, but it's good to have reached this milestone.

**Comment by fulv** [comment]
Note:  the "double jQuery" issue is still present on this branch.

```
> grep 'jQuery JavaScript' bundle.js
 * jQuery JavaScript Library v3.3.1
 * jQuery JavaScript Library v3.3.1
```

**Comment by pilz** [comment]
Note to self. To enable Cornelis to test his projects, I make a fork and adapt there, Cornelis tests the fork. If the fork is good, he manually replicates the changes to his master repo.

**Comment by fulv** [comment]
whoa!

🎆 ⚡️ :feelsgood: 😌 😆 💥 👊 👏 👯 💌 💪 👍 😂 😁 😤 🆗 👌 🙆‍♂ 🙆 🤛 👊 ✊ 🤜 🤘 😹 :octocat: 🎉 💣 🎂 🎁 💝 🎈 👑 💎 💴 💶 💷 💵 💳 💰 🎊 🎄 🎅 🤶 🎏 🏁 🌠 🏮 ㊗️ ✳️ 🔝 💟 💲

**Comment by pilz** [comment]
nice, eh? I do see some random failures on master now which don't occur locally, and may be timing issues. They are always on pat-scroll but the failing test is also changing randomly. I don't consider that a problem, but annoying.

**Comment by fulv** [comment]
Yes, I know the pat-scroll test failures, I see them randomly on local, too.
-- 
Fulvio

**Pull request merged**
