### PR TITLE
pat-gallery fixes, update masonry and imagesloaded, jQuery update

### PR DESCRIPTION
**Pull request by thet**
## pat-gallery
Fix pat-gallery to work with requirejs-text instead requirejs-tpl-jcbrand.
Fixes an obscure "window undefined" error.
Backwards incompatible change: The photoswipe-template RequireJS configuration variable is removed and a the pat-gallery-url variable is defined instead.

## pat-masonry
- While images are loading, already do masonry layouting.
- Remove the ``clear-imagesloaded-cache`` trigger, as cache functionality was removed from imagesloaded from version 3.2.0.
  See: https://github.com/desandro/imagesloaded/issues/103#issuecomment-152152568
- Change ``imagesloaded`` from usage of jQuery plugin to vanilla JavaScript to avoid timing errors, where the ``imagesloaded`` plugin wasn't available.
- Update ``masonry`` and ``imagesloaded`` plugins.

## jQuery update
- Update to jQuery 1.11.3

/cc @jcbrand

### CODE REVIEW

**Comment by thet** [comment]
Oh, it passed! I'll close #444 and update the description of this one to fit the changes made to pat-gallery.

**Comment by jcbrand** [comment]
I think since you bumped the version number, we should rather make a new release without this pull request and then merge it immediately after the release. Are you fine with that?

**Comment by thet** [comment]
absolutely fine with that.
I'm also pushing another commit, regarding masonry.

**Comment by jcbrand** [comment]
Now there are failing tests

**Comment by thet** [comment]
no more...  @jcbrand

**Comment by jcbrand** [comment]
Hi @thet I was on holiday the last week. Aiming to make a release in the next days (unless someone else jumps the gun).

**Comment by jcbrand** [comment]
I've released Patterns 2.0.14 and then manually merged in this pull request.

**Comment by thet** [comment]
tnx for merging!

**Pull request merged**
