### PR TITLE
Replicate PR #564 for pat-checked-flag

### PR DESCRIPTION
**Pull request by ale-rt**
See #564

### CODE REVIEW

**Comment by pilz** [comment]
Actually we shouldn't use pat-checked-flag anymore, it should be superseeded by pat-checklist. Where did you find it? Perhaps we can just replace it?

**Comment by cornae** [comment]
Correct.

**Comment by ale-rt** [comment]
I found it in portal stardemo. I think that pattern is triggered too easily ;) https://github.com/Patternslib/Patterns/blob/master/src/pat/checked-flag/checked-flag.js#L19

**Comment by cornae** [comment]
It must die. :)

**Comment by ale-rt** [comment]
Should I just remove it?

**Comment by pilz** [comment]
I think we should not remove it yet. Perhaps better output a warning and do another grep where it might be used. I guess I only grepped in patternslib but not in the projects, as you found this occurrence. If you just remove the pattern, things might break silently.

**Comment by ale-rt** [comment]
I think this one is silently triggered because of this line: 
```
trigger: "input[type=checkbox],input[type=radio],select",
```

**Comment by pilz** [comment]
Aaaah, in this case, it would be enough to remove the pat-checked-flag pattern from the star patterns.js, so that it doesn't get included anymore. I think that is, what you meant in your comment above, right? If so, please do.

**Comment by pilz** [comment]
I merge this as a last compatibility fix for anybody who still uses it but a note to anybody who might read this: checked-flag is deprecated and should be replaces by selectbox.

**Pull request merged**
