### PR TITLE
improved versioning process

### PR DESCRIPTION
**Pull request by witekdev**
add version.md file, prepend version number to bundle.js when creating a bundle, update release instructions.

### CODE REVIEW

**Comment by jcbrand** [comment]
Please make it VERSION.txt. It's not a markdown file, so `.md` extension is not applicable and we it's convention to rewrite it uppercase.

**Comment by jcbrand** [comment]
@cornae Something you asked for. The next version of Patternslib will have the release version at the top of the bundle.

**Comment by jcbrand** [comment]
Thanks @witekdev

**Comment by cornae** [comment]
Great!

**Pull request merged**
