### PR TITLE
gallery: allow pat-gallery trigger on image wrapper directly

### PR DESCRIPTION
**Pull request by thet**
pat-gallery: Also include the node with the ``pat-gallery`` class trigger for initializing the gallery.
Now ``pat-gallery`` can be used on anchor tags wrapping images directly, making it possible to let images be opened individually in in the overlay without adding them to a gallery with navigation controls to the next image.

### CODE REVIEW

**Comment by cornae** [comment]
Sounds great. Is the documentation also updated?

**Comment by thet** [comment]
@cornae tnx for the pointer!
I updated the PR with docs updates including info about the ``item-selector`` property, which I added in a previous PR which is already merged.

**Comment by cornae** [comment]
The property item-selector is not mentioned in the documentation on the site either: http://patternslib.com/gallery/  I'm super happy about knowing this because I posted a ticket in a project only a week ago with a request for exactly this behaviour. Very happy it's in :).

**Comment by thet** [comment]
tnx for merging!
is the documentation on http://patternslib.com/gallery/ in a separate repository?

**Comment by pysailor** [comment]
Hi @thet,
no, the documentation is fine where you put it. But http://patternslib.com/gallery/ does not update automatically.
I just updated the site, now your new documentation is there.

(Note that downloading the bundle from the site seems to be broken ATM, we'll need to fix that, also in combination with the new release #501)

**Pull request merged**
