### PR TITLE
Documentation for colour-picker

### PR DESCRIPTION
**Pull request by janga1997**
I would like any suggestions. I would also like, if there is, a reason for choosing Spectrum to base colour-picker upon.

### CODE REVIEW

**Comment by pilz** [comment]
Sorry, I don't know about the decision for spectrum. Sorry, I don't know about the decision for spectrum.

**Comment by jcbrand** [comment]
Thanks @janga1997, from what I can tell it looks good! I also don't know why spectrum was chosen, I suppose @cornae made that decision.

If we don't find a definitive answer, I propose you remove that part of the documentation again.

**Comment by cornae** [comment]
To be honest I'm not really why specifically Spectrum was chosen at the time. In general, simplicity of markup and not being depended on image files play important roles with these decisions but I'm don't know what was the case here. Would you prefer another one?

**Comment by janga1997** [comment]
@cornae I don't prefer anything. I just wanted to know if there was a reason to choose spectrum, if not, well, I would just leave out that part of the documentation.
Do you think it's a good idea to include the reasons you gave in the documentation?

**Comment by jcbrand** [comment]
@janga1997 sometimes it might be a good idea to explain why a certain library was chosen, but for now I think you can leave them out.

**Comment by jcbrand** [comment]
@janga1997 Can you make another commit to this branch to remove the `### Why did we base this library on Spectrum?` heading?

**Comment by janga1997** [comment]
@jcbrand I opened up a separate pull request. For some reason I do not have the privileges to push a branch directly to Patternslib. Maybe it has something to do with me not being a member?

**Pull request merged**
