### PR TITLE
Mutationobserver masonry

### PR DESCRIPTION
**Pull request by pilz**
Don't merge yet, this is a request for comment for now.

Attempt to implement Wichert's suggestion of mutation observers. I am looking for hints of what side effects I might have missed and might need to take into account.

We also discussed to make masonry rendering less expensive by storing if we need to recalculate at all. That is not in here yet.

### CODE REVIEW

**Comment by pilz** [comment]
Just tested with a manual build on star, it does fix the issue where the stream doesn't update when the sidebar is expanded.

**Comment by cornae** [comment]
That sounds promising. I would like to test it against many more cases in a complex product like Quaive. Is that possible?

**Comment by pilz** [comment]
Yes, I am going to mail you a ploneintranet.js to manually drop in for tests.

**Comment by pilz** [comment]
No comments and no problems found. So I will merge it now.

**Pull request merged**
