### PR TITLE
feat(pat push): Added the option to append the fetched content at the…

### LINKED ISSUE #876: push: enhance the pattern allowing to append the the fetched content to the .pat-push element
Use case:
- we have a chat window open with a lot of messages
- a new message arrive
- I want to see it pushed into my page

The current implementation of pat-push does not allow that because it will replace the content of the element all together.

### PR DESCRIPTION
**Pull request by ale-rt**
… end of the pat-push element

Fixes #876

### CODE REVIEW

**Comment by cornae** [comment]
This change is not part of the pat push pattern design and has also not been discussed in the team.

**Comment by ale-rt** [comment]
Well, I do not see any reason for this to require a brainstorming session it is a no brainer if you check the use case described in #876.
This is very demovating.

**Comment by cornae** [comment]
I read that ticket. I see many reasons @ale-rt that you don't see while there is no reason why we need this 'no brainer' now and I can explain why but not running behind pull requests, but rather in a proper team session instead. And even if there were no reasons, we have to follow the process to keep everybody on board. Also, I want to avoid the possibility of another disaster striking upon the user like what happened with the events sidebar hack.

**Comment by ale-rt** [comment]
So many interesting stories to learn about

**Comment by thet** [comment]
As part of getting a necessary feature ready to demo we need this PR to be merged.
Note: this is a technical necessity. We need to gain some knowledge about using pat-push in real environments until we can come up with better approaches.
This whole pattern is very technical and doesn't work without a proper push_kit / RabbitMQ setup anyways and is yet not promoted on the patternslib.com website. We always can fix any issues with it in upcoming versions (following semantic versioning which we do, major versions can always break backwards compatibility).

We discussed another approach of using pat-inject. This does not work in this case, as pat-push isn't using pat-inject at all.

However, this PR seems fine to me.

**Review by thet — COMMENTED** [review]
LGTM

**Comment by thet** [comment]
Maybe there was also a confusion about pat-inject push-marker. This is a different story, this PR is about pat-push.

**Pull request merged**
