### PR TITLE
pat-inject: Fix documentation about special target self and demo that behavior

### PR DESCRIPTION
**Pull request by thet**
@cornae I added a demo test case to illustrate the behavior you reported to me.
I can't reproduce it - it seems to work just fine.
Maybe the markup needs to be adapted to illustrate the misbehavior?

I need some more info to create a ticket for the problem.

### CODE REVIEW

**Comment by cornae** [comment]
I'm trying to test but make doesn't work anymore.

image

@thet Can you help out?

**Comment by thet** [comment]
@cornae I have changed the Makefile in a way, that it automatically installs "yarn" if it's not available. Please pull and try again.

**Comment by thet** [comment]
If it works I will update all other repos where yarn is used also...

**Comment by cornae** [comment]
Thanks, I'm going to try.

**Pull request merged**
