### PR TITLE
Scoped pat checkbox

### PR DESCRIPTION
**Pull request by pilz**

### CODE REVIEW

**Comment by cornae** [comment]
I see no documentation update, does that mean that the `selector:` was not needed after all?

**Comment by pilz** [comment]
Correct, I didn't need anything. At least I have a solution now that I wanted to run by you. I have extended the test page and all things there work fine and quick for me.

**Comment by cornae** [comment]
I’m very curious how you solved it :)

**Comment by cornae** [comment]
Bloody brilliant! 💃

**Pull request merged**
