### PR TITLE
Install babel to fix the travis build

### LINKED ISSUE #579: Tests are not running anymore on travis
Compare https://travis-ci.org/Patternslib/Patterns/builds/325456844 with a recent build.
The recent builds trigger this error:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at /home/travis/build/Patternslib/Patterns/src/pat/masonry/tests.js:14828
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at /home/travis/build/Patternslib/Patterns/src/pat/masonry/tests.js:14828
28 01 2018 18:37:14.962:WARN [karma]: Test suite was empty.
✖ Error while running the tests! Exit code: 0
```
I will try to use babel to transpile the bundle with babel

### PR DESCRIPTION
**Pull request by ale-rt**
Make tests work again:
```
✔ 487 tests completed
ℹ 1 test skipped
The command "make check" exited with 0.
Done. Your build exited with 0.
```

Closes #579

### CODE REVIEW

**Comment by cornae** [comment]
Is this the fix for the radio buttons?

**Comment by ale-rt** [comment]
@cornae this was to get the travis tests run again. I will now check if the produced bundle is IE11 compatible.

**Comment by ale-rt** [comment]
This looks ready to be merged.
It has indeed still test failures on IE11:
image

Be aware that this is not the fix for #577

**Comment by pilz** [comment]
IE11 tests should be fixed.

**Pull request merged**
